#define TMDSvr_VERSION_MAJOR @TMDSvr_VERSION_MAJOR@
#define TMDSvr_VERSION_MINOR @TMDSvr_VERSION_MINOR@
#define TMDSvr_VERSION_PATCH @TMDSvr_VERSION_PATCH@
#define TMDSvr_RELEASE_TYPE @TMDSvr_RELEASE_TYPE@
